/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package GDriveApps

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
  @Test
  fun getDestinationDirWithRar() {
    val classUnderTest = GDriveDn()

    val dirName = "testDir"
    val mimeType = "application/rar"
    val actualPath = GDriveDn().getDestinationDir(dirName, mimeType)

    assertEquals("F:\\Movie\\testDir", actualPath)
  }

  @Test
  fun getDestinationDirWithNonRar() {
    val classUnderTest = GDriveDn()

    val dirName = "testDir"
    val mimeType = "video/x-matroska"
    val actualPath = GDriveDn().getDestinationDir(dirName, mimeType)

    assertEquals("D:\\Ent\\gDrive_XFer\\testDir", actualPath)
  }
}
